Repository typestack/class-transformer, pull requests merged in 2018-10, with the labels that each got.

#77 Adding @TransformPlainToClass decorator
  README.md
  src/decorators.ts
  test/functional/transformer-method.spec.ts
Labels: status: fixed

#110 Fix transform of null primitive values
  src/TransformOperationExecutor.ts
  test/functional/basic-functionality.spec.ts
Labels: enhancement

#125 Polymorphism
  README.md
  src/TransformOperationExecutor.ts
  src/decorators.ts
  src/metadata/ExposeExcludeOptions.ts
  src/metadata/TypeMetadata.ts
  test/functional/custom-transform.spec.ts
Labels: enhancement, help wanted
